name: VS Code IDE Companion Extension

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'packages/vscode-ide-companion/**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Upload VSIX
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # - name: Install extension dependencies  
      #   working-directory: packages/vscode-ide-companion
      #   run: npm install

      # - name: Lint and type check
      #   working-directory: packages/vscode-ide-companion
      #   run: |
      #     npm run lint
      #     npm run check-types

      - name: Build VSIX
        working-directory: packages/vscode-ide-companion
        run: npm run package

      - name: Upload VSIX
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: gemini-cli-vscode-extension-${{ github.sha }}
          path: packages/vscode-ide-companion/*.vsix
